runtime: python311  # replace with your Python version
entrypoint: gunicorn -b :$PORT percobaan_0.wsgi

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  target_throughput_utilization: 0.6

env_variables:
  DJANGO_SETTINGS_MODULE: "percobaan_0.settings"

runtime_config:
  python_version: 3

builtins:
- django_wsgi: on

beta_settings:
    cloud_sql_instances: shaped-density-389409:us-central1:djangocoba

