# Generated by Django 4.2.1 on 2023-06-11 09:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobotIdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_field', models.DecimalField(blank=True, db_column='No.', decimal_places=65535, max_digits=65535, null=True)),
                ('nama', models.CharField(blank=True, db_column='Nama', null=True)),
                ('nilai_ideal_positif', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_ideal_negatif', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'bobot_ideal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BobotKriteriaAhp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, null=True)),
                ('nilai_performa_penjualan', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_pengetahuan_produk', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_disiplin', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_kehadiran', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_masa_kerja', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'bobot_kriteria_ahp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BobotNormalisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_field', models.DecimalField(blank=True, db_column='No.', decimal_places=65535, max_digits=65535, null=True)),
                ('nama', models.CharField(blank=True, null=True)),
                ('nilai_kehadiran', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_performa_penjualan', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_disiplin', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_masa_kerja', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_pengetahuan_produk', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'bobot_normalisasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BobotPreferensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_field', models.DecimalField(blank=True, db_column='No.', decimal_places=65535, max_digits=65535, null=True)),
                ('nama', models.CharField(blank=True, null=True)),
                ('bobo_preferensi', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'bobot_preferensi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EigenVektorAhp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, null=True)),
                ('nilai_performa_penjualan', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_pengetahuan_produk', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_disiplin', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_kehadiran', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_masa_kerja', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('jumlah', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rata_rata', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'eigen_vektor_ahp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KonsistensiAhp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perhitungan', models.CharField(blank=True, null=True)),
                ('perhitungan', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'konsistensi_ahp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KriteriaAhp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('prioritas_kriteria', models.CharField(blank=True, null=True)),
                ('kriteria', models.CharField(blank=True, null=True)),
                ('tingkat_kepentingan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kriteria_ahp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Normalisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_field', models.DecimalField(blank=True, db_column='No.', decimal_places=65535, max_digits=65535, null=True)),
                ('nama', models.CharField(blank=True, null=True)),
                ('nilai_kehadiran', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_performa_penjualan', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_disiplin', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_masa_kerja', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_pengetahuan_produk', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'normalisasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perangkingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_field', models.DecimalField(blank=True, db_column='No.', decimal_places=65535, max_digits=65535, null=True)),
                ('nama', models.CharField(blank=True, null=True)),
                ('hasil', models.DecimalField(blank=True, db_column='Hasil', decimal_places=65535, max_digits=65535, null=True)),
                ('ranking', models.DecimalField(blank=True, db_column='Ranking', decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'perangkingan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerhitunganDistanceIdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_field', models.DecimalField(blank=True, db_column='No.', decimal_places=65535, max_digits=65535, null=True)),
                ('nama', models.CharField(blank=True, null=True)),
                ('nilai_ideal_positif', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nilai_ideal_negatif', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'perhitungan_distance_ideal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('tgl_masuk', models.DateTimeField(null=True)),
                ('hari_ini', models.DateTimeField(auto_now=True)),
                ('nilai_pengetahuan_produk', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('deskripsi_pengetahuan_produk', models.CharField(blank=True, max_length=200, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Performa_Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jual_brands', models.IntegerField(null=True)),
                ('jual_brands_lain', models.IntegerField(null=True)),
                ('bulan_performa_penjualan', month.models.MonthField(default='2023-05', help_text='some help...', verbose_name='Month Value')),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_performa_penjualan', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('nilai_pengetahuan_produk', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('nilai_disiplin', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('nilai_kehadiran', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('nilai_masa_kerja', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('bulan_penilaian', month.models.MonthField(default='2023-05', help_text='some help...', verbose_name='Month Value')),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari_masuk', models.IntegerField(null=True)),
                ('banyak_hari', models.IntegerField(null=True)),
                ('bulan_kehadiran', month.models.MonthField(default='2023-05', help_text='some help...', verbose_name='Month Value')),
                ('hari_libur', models.IntegerField(null=True)),
                ('hari_cuti', models.IntegerField(null=True)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disiplin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuota_disiplin', models.IntegerField(null=True)),
                ('nilai_pelanggaran', models.IntegerField(null=True)),
                ('bulan_disiplin', month.models.MonthField(default='2023-05', help_text='some help...', verbose_name='Month Value')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
