# Generated by Django 4.2.2 on 2023-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nilai_pengetahuan_produk',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
    ]
