# Generated by Django 4.2.2 on 2023-06-19 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_nilai_pengetahuan_produk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai_Ahp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kriteria', models.IntegerField(null=True)),
                ('value_kriteria', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
