# Generated by Django 4.2.2 on 2023-06-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_nilai_ahp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilai_ahp',
            name='nama',
        ),
        migrations.AlterField(
            model_name='nilai_ahp',
            name='nama_kriteria',
            field=models.CharField(null=True),
        ),
    ]
