# Generated by Django 4.2.2 on 2023-06-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_nilai_ahp_nama_alter_nilai_ahp_nama_kriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai_ahp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
