# Generated by Django 4.2.2 on 2023-06-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_nilai_ahp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komparasi_Ahp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kriteria', models.CharField(null=True)),
                ('value_kriteria', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
    ]
