# Generated by Django 4.2.2 on 2023-06-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_komparasi_ahp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai_ahp',
            name='nama_kriteria',
            field=models.CharField(blank=True, null=True),
        ),
    ]
