# Generated by Django 4.2.2 on 2023-06-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_nilai_ahp_nama_kriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai_ahp',
            name='value_kriteria',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
